### ISSUE TITLE
Roadmap for this project?

### ISSUE THREAD

**Issue by rclark** [aws-cloudformation/aws-cloudformation-template-schema#38]
Sorry for the existential question... But does this project have a future? 

If the primary intent is to provide code-completion in VS Code, does this end up landing in the [AWS Toolkit for VS Code](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/welcome.html)?

**Comment by PatMyron** [comment]
It's currently used in [CloudFormation's VS Code extension](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code)

AWS Toolkit CloudFormation support is being discussed and considered as well

**Comment by rclark** [comment]
Thanks!
